name: vhcsite
description: Website for VHCBlade!

publish_to: 'none' 
version: 3.3.2

environment:
  sdk: ">=2.17.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.15.0

  event_bloc: ^4.5.1
  event_essay: ^0.1.5
  # event_essay:
  #   path: ../../../event_essay
  event_navigation: ^0.6.6
  event_db: ^0.1.5
  vhcblade_theme: ^0.2.4
  # vhcblade_theme: 
  #   path: ../../../vhcblade_theme

  flutter_markdown: ^0.6.14
  intl: ^0.18.1
  provider: ^6.0.0
  tuple: ^2.0.0
  universal_html: ^2.0.0
  url_launcher: ^6.0.0

dev_dependencies:
  event_db_tester: ^0.1.0

  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - CHANGELOG.md
    - assets/img/
    - assets/img/about/
    - assets/img/apps/
    - assets/text/about/
    - assets/text/apps/
    # Blog
    - assets/text/manifest.json
    - assets/text/blog/
    - assets/text/blog/flutter/
    - assets/text/blog/games/
    - assets/text/blog/life/