name: vhcsite
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.1
  provider: ^4.0.0
  url_launcher: ^5.0.0
  flutter_linkify: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true