name: vhcsite
description: Website for VHCBlade!

publish_to: 'none' 
version: 1.2.0

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^5.0.0-nullsafety.0
  url_launcher: ^6.0.0-nullsafety.0
  animations: ^2.0.0-nullsafety.0
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - CHANGELOG
    - assets/img/
    - assets/img/about/
    - assets/text/about/
    - assets/text/dev/flutter/state/
    - assets/img/dev/flutter/state/